name: Test Project

on:
  push:
    branches: [ main ] # Or whatever your main branch is called

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 20.x # Recommended to use a broader version for stability

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
